// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnRHZiJoFAyAJMptt6iIAWUoYMf-TgmI',
    appId: '1:614395199555:web:bba4f607c1719feb7154f6',
    messagingSenderId: '614395199555',
    projectId: 'instagram-stg',
    authDomain: 'instagram-stg.firebaseapp.com',
    storageBucket: 'instagram-stg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27vyjV-OFVT-hbcw1QTeNm0liq08KU9s',
    appId: '1:614395199555:android:4bbabe9bf23b04637154f6',
    messagingSenderId: '614395199555',
    projectId: 'instagram-stg',
    storageBucket: 'instagram-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASScf3ddlRDPdReuInQNCmJ07VPQelpsE',
    appId: '1:614395199555:ios:70da18fa4bae205d7154f6',
    messagingSenderId: '614395199555',
    projectId: 'instagram-stg',
    storageBucket: 'instagram-stg.appspot.com',
    iosClientId: '614395199555-27i44ce8aik6s87tckm727rmhf0t1o96.apps.googleusercontent.com',
    iosBundleId: 'com.sambath.instagram.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASScf3ddlRDPdReuInQNCmJ07VPQelpsE',
    appId: '1:614395199555:ios:70da18fa4bae205d7154f6',
    messagingSenderId: '614395199555',
    projectId: 'instagram-stg',
    storageBucket: 'instagram-stg.appspot.com',
    iosClientId: '614395199555-27i44ce8aik6s87tckm727rmhf0t1o96.apps.googleusercontent.com',
    iosBundleId: 'com.sambath.instagram.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDnRHZiJoFAyAJMptt6iIAWUoYMf-TgmI',
    appId: '1:614395199555:web:c7ddafe20d9e5e367154f6',
    messagingSenderId: '614395199555',
    projectId: 'instagram-stg',
    authDomain: 'instagram-stg.firebaseapp.com',
    storageBucket: 'instagram-stg.appspot.com',
  );
}
