// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-OmnG9jzs2IkvQZsWzj85i1eqt62x_pI',
    appId: '1:174842870019:web:0a3390ee4598df37bb1136',
    messagingSenderId: '174842870019',
    projectId: 'instagram-prod-d9fab',
    authDomain: 'instagram-prod-d9fab.firebaseapp.com',
    storageBucket: 'instagram-prod-d9fab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTeFWsqxhdXIPHoIa2xdGksWIVaxKs1TQ',
    appId: '1:174842870019:android:60db7cfb56cb1234bb1136',
    messagingSenderId: '174842870019',
    projectId: 'instagram-prod-d9fab',
    storageBucket: 'instagram-prod-d9fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUfaH9SgM9bGHv9NmBFhVLMHSrH2k4ids',
    appId: '1:174842870019:ios:22f6faa4c3eacf91bb1136',
    messagingSenderId: '174842870019',
    projectId: 'instagram-prod-d9fab',
    storageBucket: 'instagram-prod-d9fab.appspot.com',
    iosClientId: '174842870019-jq7409datkjrp2hqjgo0oq4ce53rf9um.apps.googleusercontent.com',
    iosBundleId: 'com.sambath.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUfaH9SgM9bGHv9NmBFhVLMHSrH2k4ids',
    appId: '1:174842870019:ios:22f6faa4c3eacf91bb1136',
    messagingSenderId: '174842870019',
    projectId: 'instagram-prod-d9fab',
    storageBucket: 'instagram-prod-d9fab.appspot.com',
    iosClientId: '174842870019-jq7409datkjrp2hqjgo0oq4ce53rf9um.apps.googleusercontent.com',
    iosBundleId: 'com.sambath.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-OmnG9jzs2IkvQZsWzj85i1eqt62x_pI',
    appId: '1:174842870019:web:1e2371bbb969db72bb1136',
    messagingSenderId: '174842870019',
    projectId: 'instagram-prod-d9fab',
    authDomain: 'instagram-prod-d9fab.firebaseapp.com',
    storageBucket: 'instagram-prod-d9fab.appspot.com',
  );
}
